/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hf.api.integration

import hf.api.api.cardListLens
import org.http4k.core.Method
import org.http4k.core.Request
import org.http4k.core.Status
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest : BaseIntegrationTest() {

//    @Test
//    fun `can fetch a deck`() {
//        val request = Request(Method.GET, "http://localhost:$testPort/deck")
//
//        val resp = client(request)
//        assertNotNull(resp)
//        assertEquals(Status.OK, resp.status)
//
//        val cards = cardListLens(resp)
//        assertEquals(54, cards.size)
//    }
}
